package com.svalero.aa2.util;

public class Util {
    public String[] exportArtworkToCSVHeaders() {
        return new String[] {
                "id",
                "api model",
                "api link",
                "is boosted",
                "title",
                "alt titles",
                "thumbnail",
                "main reference number",
                "has not been viewed much",
                "boost rank",
                "date start",
                "date end",
                "date display",
                "date qualifier title",
                "date qualifier id",
                "artist display",
                "place of origin",
                "dimensions",
                "dimenstions detail",
                "medium display",
                "inscriptions",
                "credit line",
                "catalogue display",
                "publication history",
                "exhibition history",
                "provenance text",
                "edition",
                "publishing verification level",
                "internal department id",
                "fiscal year",
                "fiscal year deaccession",
                "is public domain",
                "is zoomable",
                "max zoom window size",
                "copyright notice",
                "has multimedia resources",
                "has educational resources",
                "has advanced imaging",
                "colorfulness",
                "color",
                "latitude",
                "longitude",
                "latlon",
                "is on view",
                "on loan display",
                "gallery title",
                "gallery id",
                "artwork type title",
                "artwork type id",
                "department title",
                "department id",
                "artist id",
                "artist title",
                "alt artist ids",
                "artist ids",
                "artist titles",
                "category ids",
                "category titles",
                "term titles",
                "style id",
                "style title",
                "alt style ids",
                "style ids",
                "style titles",
                "classification id",
                "classification title",
                "alt classification ids",
                "classification ids",
                "classification titles",
                "subject id",
                "alt subject ids",
                "subjects ids",
                "subject titles",
                "material id",
                "alt material ids",
                "material ids",
                "material titles",
                "technique id",
                "alt technique ids",
                "technique ids",
                "technique titles",
                "theme titles",
                "image id",
                "alt image ids",
                "document ids",
                "sound ids",
                "video ids",
                "text ids",
                "section ids",
                "section titles",
                "site ids",
                "source updated at",
                "updated at",
                "timestamp",
        };
    }

    public String[] exportExhibitionToCSVHeaders() {
        return new String[] {
                "id",
                "api model",
                "api link",
                "title",
                "is featured",
                "short description",
                "web url",
                "image url",
                "status",
                "aic start at",
                "aid end at",
                "gallery id",
                "gallery title",
                "artwork ids",
                "artwork titles",
                "artist ids",
                "site ids",
                "image id",
                "alt image ids",
                "document ids",
                "source updated at",
                "updated at",
                "timestamp",
        };
    }

}
